/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Introduction',
    },
    {
      type: 'doc',
      id: 'pd-platforms',
      label: 'Platforms',
    },
    {
      type: 'category',
      label: 'Getting Started',
      link: {
        "type": "generated-index",
        "description": "Embed Powerful AI Agents into Your Website"
      },
      items: [
        {
          type: 'doc',
          id: 'getting-started/create-agent',
          label: 'Create Chatbot Agent'
        },
        {
          type: 'doc',
          id: 'getting-started/choose-channel',
          label: 'Choose Channel'
        },
      ],
    },
    {
      type: 'category',
      label: 'Channels',
      link: {
        type: 'generated-index',
        description: 'Channels to connect your agents with users.',
      },
      items: [
        {
          type: 'category',
          label: 'Web',
          items: [
            'channels/web/index',
            'channels/web/embed-widget',
            {
              type: 'category',
              label: 'Widgets',
              link: {
                type: 'generated-index',
                description: 'Different widget types for embedding your AI agent on websites.',
              },
              items: [
                'channels/web/widgets/bubble',
                'channels/web/widgets/popup',
                'channels/web/widgets/standard',
              ]
            },
            'channels/web/streaming',
            'channels/web/theme',
            'channels/web/custom-css',
            {
              type: 'category',
              label: 'Advanced Usage',
              link: {
                type: 'generated-index',
                description: 'This section covers advanced features and programmatic control options available across the web widget types (Standard, Bubble, and Popup).',
              },
              items: [
                'channels/web/advanced-usage/onsend-callback',
              ]
            }
          ]
        },
        {
          type: 'category',
          label: 'WhatsApp',
          items: [
            {
              type: 'category',
              label: 'Business Setup',
              items: [
                'channels/whatsapp/business-setup/create-a-business-account',
                'channels/whatsapp/business-setup/create-a-meta-app',
                'channels/whatsapp/business-setup/generate-whatsapp-token',
                'channels/whatsapp/business-setup/add-phone-number',
              ]
            },
            'channels/whatsapp/quick-start',
          ]
        }
      ],
    },
    {
      type: 'category',
      label: 'Providers',
      link: {
        type: 'generated-index',
        description: 'Integrations with language‑model providers.',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'providers',
        },
      ],
    },
    {
      type: 'category',
      label: 'Tools',
      link: {
        type: 'generated-index',
        description: 'AI tool capabilities for enhancing your agents.',
      },
      items: [
        'tools/overview',
        'tools/function-calling',
        'tools/file-search',
      ],
    },
    {
      type: 'category',
      label: 'Features',
      link: {
        type: 'generated-index',
        description: 'Features of Predictable Dialogs.',
      },
      items: [
        'features/api-keys',
        'features/sessions',
        'features/reports',
      ],
    },
    {
          type: 'category',
          label: "API Reference (Beta)",
          link: {
            "type": "generated-index",
            "description": "Management API for agents"
          },
          items: [
            {
              type: 'doc',
              id: 'api-reference/introduction',
              label: 'Introduction'
            },
            {
              type: 'doc',
              id: 'api-reference/authentication',
              label: 'Authentication'
            },
            {
              type: 'doc',
              id: 'api-reference/making-requests',
              label: 'Making Requests'
            },
            {
              type: 'doc',
              id: 'api-reference/endpoints',
              label: 'Endpoints'
            },
          ],
        },
    {
      type: 'doc',
      id: 'quick-faq',
      label: 'FAQs',
    },
  ],

};

export default sidebars;
