/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Introduction',
    },
    {
      type: 'category',
      label: 'Getting Started',
      link: {
        "type": "generated-index",
        "description": "Connect your OpenAI Assistant to your website"
      },   
      items: [
        {
          type: 'doc',
          id: 'getting-started/prerequisites',
          label: 'Prerequisites' 
        },
        {
          type: 'doc',
          id: 'getting-started/creating-an-agent',
          label: 'Creating an Agent' 
        },

        {
        type: 'doc',
        id: 'getting-started/embedding-your-openai-assistant',
        label: 'Embedding Your OpenAI Assistant' 
        } 
      ],
    },
    {
      type: 'doc',
      id: 'theme',
      label: 'Theme',
    },
    {
      type: 'doc',
      id: 'settings',
      label: 'Settings',
    },

    {
      type: 'category',
      label: "WhatsApp Business Setup",
      link: {
        "type": "generated-index",
        "description": "Setup your WhatsApp business account."
      },   
      items: [
        'whatsapp/create-a-business-account',
        {
          type: 'doc',
          id: 'whatsapp/create-a-meta-app',
          label: 'Create a Meta App' 
        },
        {
          type: 'doc',
          id: 'whatsapp/generate-whatsapp-token',
          label: 'Generate a WhatsApp Token' 
        },
        {
          type: 'doc',
          id: 'whatsapp/add-phone-number',
          label: 'Add a Phone Number' 
        }   
      ],
    },

    // {
    //   type: 'autogenerated', 
    //   dirName: '.',
      
    // }
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
